# Generated by Django 3.1 on 2020-08-13 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='eventlocation',
            options={'verbose_name': 'Event Location', 'verbose_name_plural': 'Event Locations'},
        ),
        migrations.AlterModelOptions(
            name='guest',
            options={'verbose_name': 'Guest', 'verbose_name_plural': 'Guests'},
        ),
        migrations.AlterModelOptions(
            name='guestattendance',
            options={'verbose_name': 'Guest Attendance', 'verbose_name_plural': 'Guest Attendances'},
        ),
        migrations.AlterModelOptions(
            name='host',
            options={'verbose_name': 'Host', 'verbose_name_plural': 'Hosts'},
        ),
        migrations.AlterModelOptions(
            name='hostattendance',
            options={'verbose_name': 'Host Attendance', 'verbose_name_plural': 'Host Attendances'},
        ),
        migrations.AlterModelOptions(
            name='preregistration',
            options={'verbose_name': 'Pre-registration', 'verbose_name_plural': 'Pre-registrations'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='guest',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='guestattendance',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_attendances', to='api.event'),
        ),
        migrations.AlterField(
            model_name='hostattendance',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_attendances', to='api.event'),
        ),
    ]
