# Generated by Django 3.1 on 2020-08-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200813_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.CharField(default='kekko', max_length=32),
            preserve_default=False,
        ),
    ]
