# Generated by Django 3.1 on 2020-08-17 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200817_1922'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GuestAttendance',
            new_name='GuestRSVP',
        ),
        migrations.RenameModel(
            old_name='HostAttendance',
            new_name='HostRSVP',
        ),
        migrations.AlterModelOptions(
            name='guestrsvp',
            options={'verbose_name': 'Guest RSVP', 'verbose_name_plural': "Guest RSVP's"},
        ),
        migrations.AlterModelOptions(
            name='hostrsvp',
            options={'verbose_name': 'Host RSVP', 'verbose_name_plural': "Host RSVP's"},
        ),
        migrations.AlterModelTable(
            name='guestrsvp',
            table='guest_rsvp',
        ),
        migrations.AlterModelTable(
            name='hostrsvp',
            table='host_rsvp',
        ),
    ]
