# Generated by Django 3.1 on 2020-08-17 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200817_2015'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GuestGradeLevel',
            new_name='GuestGrade',
        ),
        migrations.AlterModelTable(
            name='guestgrade',
            table='guest_grade',
        ),
    ]
