# Generated by Django 3.1 on 2020-08-17 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200817_2046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guestgrade',
            options={'verbose_name': 'Guest Grade', 'verbose_name_plural': 'Guest Grades'},
        ),
    ]
