# Generated by Django 3.1 on 2020-08-18 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_guestgrade_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='hide',
        ),
        migrations.RemoveField(
            model_name='event',
            name='show',
        ),
    ]
