# Generated by Django 3.1 on 2020-08-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200818_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='phone number'),
        ),
    ]
