# Generated by Django 3.1 on 2020-09-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_host_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['pk'], 'verbose_name': 'Registration', 'verbose_name_plural': 'Registrations'},
        ),
        migrations.AddField(
            model_name='event',
            name='collect_guest_names',
            field=models.BooleanField(default=False),
        ),
    ]
