# Generated by Django 3.1 on 2020-09-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200903_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='excerpt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
