# Generated by Django 3.1 on 2020-09-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_event_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='children_only',
            field=models.BooleanField(default=True),
        ),
    ]
