# Generated by Django 3.1 on 2020-09-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_event_children_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='custom_email_subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='use_custom_email_subject',
            field=models.BooleanField(default=False),
        ),
    ]
