# Generated by Django 3.1.1 on 2020-09-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20200904_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestgrade',
            name='order',
            field=models.IntegerField(default=-1),
        ),
    ]
